application:
  name: "\${spring.application.name}"

server:
  error:
    include-stacktrace: never

spring:
  application:
    name: Calcula-AI-API
  rabbitmq:
    host: "\${RABBITMQ_HOST:localhost}"
    port: "\${RABBITMQ_PORT:5672}"
    virtual-host: "\${RABBITMQ_VIRTUAL_HOST:/}"
    username: "\${RABBITMQ_USERNAME:guest}"
    password: "\${RABBITMQ_PASSWORD:guest}"
  data:
    redis:
      url: "\${REDIS_URL:redis://localhost:6379}"
      database: "\${REDIS_DATABASE:0}"
      timeout: 60000

rabbitmq:
  queues:
    process-photo:
      exchange: "\${RABBITMQ_EXCHANGE_PROCESS_PHOTO:calcula-ai}"
      routing-key: "\${RABBITMQ_QUEUE_PROCESS_PHOTO:process-photo}"
      queue: "\${RABBITMQ_QUEUE_PROCESS_PHOTO:process-photo-queue}"

minio:
  access-key: "\${MINIO_ACCESS_KEY}"
  secret-key: "\${MINIO_SECRET_KEY}"
  endpoint: "\${MINIO_ENDPOINT}"

logstash:
  url: "\${LOGSTASH_URL:localhost}"
  port: "\${LOGSTASH_PORT:5000}"
  token: "\${LOGSTASH_TOKEN:xxx}"
  env: "\${ENV:dev}"